server:
  port: 9999

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/xdb?serveTimezone=GMT%2B8

  redis:
    host: localhost
    port: 6379
    timeout: 1000
    jedis:
      pool:
        max-idle: 10
        min-idle: 5
        max-wait: -1

logging:
  level:
    com.david: debug